export const tokens = {
  colors: {
    // Primitives
    'brand-900': 'text-blue-900',
    'brand-700': 'text-blue-700',
    'brand-600': 'text-blue-600',
    'brand-500': 'text-blue-500',
    'brand-100': 'text-blue-100',
    'brand-50': 'text-blue-50',
    'neutral-900': 'text-gray-900',
    'neutral-700': 'text-gray-700',
    'neutral-600': 'text-gray-600',
    'neutral-500': 'text-gray-500',
    'neutral-400': 'text-gray-400',
    'white': 'text-white',
    'black': 'text-black',

    // Semantic Aliases
    'text-primary': 'text-gray-900',
    'text-secondary': 'text-gray-600',
    'text-tertiary': 'text-gray-400',
    'text-inverse': 'text-white',
    'text-brand': 'text-blue-600',
    'text-brand-dark': 'text-blue-900',
  },
  backgrounds: {
    // Primitives
    'bg-brand-900': 'bg-blue-900',
    'bg-brand-700': 'bg-blue-700',
    'bg-brand-600': 'bg-blue-600',
    'bg-brand-500': 'bg-blue-500',
    'bg-brand-100': 'bg-blue-100',
    'bg-brand-50': 'bg-blue-50',
    'bg-neutral-900': 'bg-gray-900',
    'bg-neutral-800': 'bg-gray-800',
    'bg-neutral-200': 'bg-gray-200',
    'bg-neutral-100': 'bg-gray-100',
    'bg-neutral-50': 'bg-gray-50',
    'bg-white': 'bg-white',
    'bg-black': 'bg-black',

    // Semantic Aliases
    'bg-surface': 'bg-white',
    'bg-surface-alt': 'bg-gray-50',
    'bg-surface-dark': 'bg-gray-900',
    'bg-primary': 'bg-blue-600',
    'bg-secondary': 'bg-gray-200',
    'bg-elevated': 'bg-white',
  },
  spacing: {
    'none': '0',
    'xs': '4px',
    'sm': '8px',
    'md': '16px',
    'lg': '24px',
    'xl': '32px',
    '2xl': '48px',
    '3xl': '64px',
    '4xl': '80px',
    '5xl': '96px',
    '6xl': '128px',
    
    // Negative Spacing
    '-xs': '-4px',
    '-sm': '-8px',
    '-md': '-16px',
    '-lg': '-24px',
    '-xl': '-32px',
  },
  sectionPadding: {
    'sm': 'py-8 px-4',
    'md': 'py-16 px-6',
    'lg': 'py-24 px-8',
    'xl': 'py-32 px-10',
  },
  containerPadding: {
    'sm': 'px-4',
    'md': 'px-8',
    'lg': 'px-12',
    'xl': 'px-16',
  },
  typography: {
    // Display (9xl - 5xl) - Monotonic Scale
    'display-3xl': 'text-9xl font-bold tracking-tight',
    'display-2xl': 'text-8xl font-bold tracking-tight',
    'display-xl': 'text-7xl font-bold tracking-tight',
    'display-lg': 'text-6xl font-bold tracking-tight',
    'display-md': 'text-5xl font-bold tracking-tight',
    'display-sm': 'text-5xl font-bold tracking-tight', 

    // Heading (4xl - lg) - No Overlap with Display
    'heading-xl': 'text-4xl font-bold',
    'heading-lg': 'text-3xl font-bold',
    'heading-md': 'text-2xl font-bold',
    'heading-sm': 'text-xl font-bold',
    'heading-xs': 'text-lg font-bold',

    // Body (xl - sm) - No Overlap with Heading
    'body-xl': 'text-xl',
    'body-lg': 'text-lg',
    'body-md': 'text-base',
    'body-sm': 'text-sm',
    
    // Utilities
    'caption': 'text-sm text-gray-500',
    'eyebrow': 'text-xs font-bold uppercase tracking-wider text-gray-500',
    'lead': 'text-xl text-gray-600 leading-relaxed',
    
    // Buttons
    'button-lg': 'text-lg font-medium',
    'button-md': 'text-base font-medium',
    'button-sm': 'text-sm font-medium',
  },
  fontSize: {
    'xs': 'text-xs',
    'sm': 'text-sm',
    'base': 'text-base',
    'lg': 'text-lg',
    'xl': 'text-xl',
    '2xl': 'text-2xl',
    '3xl': 'text-3xl',
    '4xl': 'text-4xl',
    '5xl': 'text-5xl',
    '6xl': 'text-6xl',
    '7xl': 'text-7xl',
    '8xl': 'text-8xl',
    '9xl': 'text-9xl',
  },
  fontFamily: {
    'sans': 'font-sans',
    'serif': 'font-serif',
    'mono': 'font-mono',
  },
  lineHeight: {
    'none': 'leading-none',
    'tight': 'leading-tight',
    'snug': 'leading-snug',
    'normal': 'leading-normal',
    'relaxed': 'leading-relaxed',
    'loose': 'leading-loose',
  },
  fontWeight: {
    'thin': 'font-thin',
    'extralight': 'font-extralight',
    'light': 'font-light',
    'normal': 'font-normal',
    'medium': 'font-medium',
    'semibold': 'font-semibold',
    'bold': 'font-bold',
    'extrabold': 'font-extrabold',
    'black': 'font-black',
  },
  radius: {
    'none': 'rounded-none',
    'sm': 'rounded-sm',
    'md': 'rounded-md',
    'lg': 'rounded-lg',
    'xl': 'rounded-xl',
    '2xl': 'rounded-2xl',
    '3xl': 'rounded-3xl',
    'full': 'rounded-full',
  },
  shadow: {
    'none': 'shadow-none',
    'sm': 'shadow-sm',
    'md': 'shadow-md',
    'lg': 'shadow-lg',
    'xl': 'shadow-xl',
    '2xl': 'shadow-2xl',
    'inner': 'shadow-inner',
  },
  maxWidth: {
    'sm': 'max-w-screen-sm',
    'md': 'max-w-screen-md',
    'lg': 'max-w-screen-lg',
    'xl': 'max-w-screen-xl',
    '2xl': 'max-w-screen-2xl',
    'full': 'max-w-full',
    'prose': 'max-w-prose',
    'min': 'max-w-min',
    'max': 'max-w-max',
    'fit': 'max-w-fit',
    'screen': 'max-w-screen',
  },
  width: {
    'full': 'w-full',
    'screen': 'w-screen',
    'auto': 'w-auto',
    'fit': 'w-fit',
    'min': 'w-min',
    'max': 'w-max',
    '1/2': 'w-1/2',
    '1/3': 'w-1/3',
    '2/3': 'w-2/3',
    '1/4': 'w-1/4',
    '3/4': 'w-3/4',
    '1/5': 'w-1/5',
    '2/5': 'w-2/5',
    '3/5': 'w-3/5',
    '4/5': 'w-4/5',
  },
  height: {
    'auto': 'h-auto',
    'full': 'h-full',
    'screen': 'h-screen',
    'fit': 'h-fit',
    'min': 'h-min',
    'max': 'h-max',
    '1/2': 'h-1/2',
    '1/3': 'h-1/3',
    '2/3': 'h-2/3',
    '1/4': 'h-1/4',
    '3/4': 'h-3/4',
  },
  aspectRatio: {
    'auto': 'aspect-auto',
    'square': 'aspect-square',
    'video': 'aspect-video',
    'video-16-9': 'aspect-[16/9]', // Explicit
    '4/3': 'aspect-[4/3]',
    '21/9': 'aspect-[21/9]',
  },
  opacity: {
    '0': 'opacity-0',
    '5': 'opacity-5',
    '10': 'opacity-10',
    '20': 'opacity-20',
    '25': 'opacity-25',
    '30': 'opacity-30',
    '40': 'opacity-40',
    '50': 'opacity-50',
    '60': 'opacity-60',
    '70': 'opacity-70',
    '75': 'opacity-75',
    '80': 'opacity-80',
    '90': 'opacity-90',
    '95': 'opacity-95',
    '100': 'opacity-100',
  },
  zIndex: {
    '0': 'z-0',
    '10': 'z-10',
    '20': 'z-20',
    '30': 'z-30',
    '40': 'z-40',
    '50': 'z-50',
    'auto': 'z-auto',
  },
  border: {
    width: {
      '0': 'border-0',
      '1': 'border',
      '2': 'border-2',
      '4': 'border-4',
      '8': 'border-8',
    },
    color: {
      'brand-500': 'border-blue-500',
      'neutral-200': 'border-gray-200',
      'transparent': 'border-transparent',
      'border-subtle': 'border-gray-200',
      'border-strong': 'border-gray-400',
    },
    style: {
      'solid': 'border-solid',
      'dashed': 'border-dashed',
      'dotted': 'border-dotted',
      'double': 'border-double',
      'none': 'border-none',
    }
  },
  transition: {
    'none': 'transition-none',
    'all': 'transition-all',
    'default': 'transition',
    'colors': 'transition-colors',
    'opacity': 'transition-opacity',
    'shadow': 'transition-shadow',
    'transform': 'transition-transform',
  },
  easing: {
    'linear': 'ease-linear',
    'in': 'ease-in',
    'out': 'ease-out',
    'in-out': 'ease-in-out',
  },
  breakpoints: {
    'sm': '640px',
    'md': '768px',
    'lg': '1024px',
    'xl': '1280px',
    '2xl': '1536px',
  },
  grid: {
    columns: {
      '1': 'grid-cols-1',
      '2': 'grid-cols-2',
      '3': 'grid-cols-3',
      '4': 'grid-cols-4',
      '5': 'grid-cols-5',
      '6': 'grid-cols-6',
      '12': 'grid-cols-12',
    },
    gap: {
      'sm': 'gap-2',
      'md': 'gap-4',
      'lg': 'gap-8',
      'xl': 'gap-12',
    }
  }
};

export type ThemeTokens = typeof tokens;
